import Head from 'next/head'
import Filter from '@/components/Filter'
import Header from '@/components/Header'
import { Button, Col, Layout, List, Row } from 'antd'
import Map from '@/components/Map'
import { useEffect, useLayoutEffect } from 'react'
import warehousesSlice from "@/store/warehouses.slice"
import { observer } from 'mobx-react-lite'
import 'leaflet/dist/leaflet.css'
import Calculator from '@/components/Calculator'

export default observer(function Home() {

  useEffect(() => {
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />

        <Row gutter={[24, 0]} className="pt-10">
          <Col span={15}>
            <Map />
          </Col>
          <Col span={9} order={2}>
            <Filter />
          </Col>
        </Row>

        <List
          itemLayout="horizontal"
          dataSource={warehousesSlice.filteredWarehouses}
          renderItem={(item, index) => (
            <List.Item key={item.id}>
              <List.Item.Meta title={item.title} description={<ListItemDescription address={item.address} contacts={item.contacts} />} />
            </List.Item>
          )}
        />

        <Calculator />
      </Layout>
    </>
  )
})


const ListItemDescription = ({ address, contacts }: any) => {
  return (
    <Layout style={{ width: '100%', display: 'flex', flexDirection: 'row', gap: '30px', justifyContent: 'space-between' }}>
      <Row style={{ width: '100%' }} wrap={true} align="middle" justify="space-between">
        <Col span={8}>
          {address.region.type + " "}
          {address.region.name + ", "}
          {address.locality.type + " "}
          {address.locality.name + ", "}
          {address.street.type + " "}
          {address.street.name + ", "}
          {"дом " + address.street.number}
        </Col>
        <Col span={6}>
          {contacts.phones[0].phone}
          {contacts.emails[0].email}
        </Col>
        <Col span={2}>
          <Button type='primary'>Перейти</Button>
        </Col>
      </Row>
    </Layout>
  )


}
